"""Ground-truth insight set ("answer key") for the evaluation harness.

The answer key is generated by running the detectors at STRICT thresholds on the
full dataset — only high-confidence, clearly-valuable patterns survive — then
written to JSON for the analyst to hand-edit (toggle ``include``, adjust
``validity``, or add manual entries). The evaluator scores each approach's recall
against this set.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

import pandas as pd

from .detectors import run_all
from .findings import Finding

# Stricter overrides layered on top of the user's detector config: fewer, surer hits.
STRICT_OVERRIDES: dict[str, dict[str, Any]] = {
    "fragmented_orders": {"min_orders": 5},
    "supplier_concentration": {"share_threshold": 0.45, "hhi_threshold": 0.27},
    "maverick_price_variance": {"variance_pct": 0.20},
    "tail_spend": {},
    "single_source_risk": {"min_spend": 50000.0},
    "timing_anomaly": {"end_of_period_share": 0.45},
    "duplicate_order": {},
}


def _strict_cfg(detector_cfg: dict[str, Any]) -> dict[str, Any]:
    out = copy.deepcopy(detector_cfg or {})
    for name, ov in STRICT_OVERRIDES.items():
        out.setdefault(name, {})
        out[name].update(ov)
    return out


def build_answer_key(df: pd.DataFrame, detector_cfg: dict[str, Any]) -> list[dict[str, Any]]:
    """Return answer-key entries (list of dicts) from strict-threshold detectors."""
    findings = run_all(df, _strict_cfg(detector_cfg))
    entries = []
    for f in findings:
        entries.append(
            {
                "key": f.key(),
                "type": f.type,
                "entities": f.entities,
                "metrics": f.metrics,
                "est_impact_usd": f.est_impact_usd,
                "one_line": f.one_line,
                "include": True,      # set False to drop from ground truth
                "validity": 2,        # analyst override: 0 wrong / 1 trivial / 2 valuable
            }
        )
    return entries


def write_answer_key(entries: list[dict[str, Any]], path: str | Path) -> None:
    payload = {
        "_README": (
            "Hand-edit this file: set include=false to drop an entry from ground truth, "
            "set validity to 0 (wrong) / 1 (trivial) / 2 (valuable). Add your own entries "
            "in the same shape. 'key' is type::entities and is used for coverage matching."
        ),
        "entries": entries,
    }
    Path(path).write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")


def load_answer_key(path: str | Path) -> list[dict[str, Any]]:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    entries = data.get("entries", [])
    return [e for e in entries if e.get("include", True)]
